# Generated by Django 4.0.3 on 2022-09-28 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 28, 17, 52, 49, 721176, tzinfo=utc)),
        ),
    ]
